name: Build Release App Bundle

on: workflow_dispatch

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Decode Keystore
#        id: decode_keystore
#        uses: timheuer/base64-to-file@v1
#        with:
#          fileName: 'keystore/key-r.jks'
#          encodedString: ${{ secrets.KEYSTORE_FILE }}


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_FILE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/key-r.jks

      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build prod
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: app/build/outputs/